// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3Ij3snenH34bDs12_Lfb_FFmkLvAA',
    appId: '1:788742862967:web:your-web-app-id',
    messagingSenderId: '788742862967',
    projectId: 'birdify-df029',
    authDomain: 'birdify-df029.firebaseapp.com',
    storageBucket: 'birdify-df029.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3Ij3snenH34bDs12_Lfb_FFmkLvAA',
    appId: '1:788742862967:android:e696a8bdc40772aceb2e72',
    messagingSenderId: '788742862967',
    projectId: 'birdify-df029',
    storageBucket: 'birdify-df029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3Ij3snenH34bDs12_Lfb_FFmkLvAA',
    appId: '1:788742862967:ios:your-ios-app-id',
    messagingSenderId: '788742862967',
    projectId: 'birdify-df029',
    storageBucket: 'birdify-df029.firebasestorage.app',
    iosClientId: 'your-ios-client-id-here',
    iosBundleId: 'com.example.appbirdify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3Ij3snenH34bDs12_Lfb_FFmkLvAA',
    appId: '1:788742862967:macos:your-macos-app-id',
    messagingSenderId: '788742862967',
    projectId: 'birdify-df029',
    storageBucket: 'birdify-df029.firebasestorage.app',
    iosClientId: 'your-ios-client-id-here',
    iosBundleId: 'com.example.appbirdify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3Ij3snenH34bDs12_Lfb_FFmkLvAA',
    appId: '1:788742862967:windows:your-windows-app-id',
    messagingSenderId: '788742862967',
    projectId: 'birdify-df029',
    storageBucket: 'birdify-df029.firebasestorage.app',
  );
} 