name: iOS TestFlight

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build IPA (release)
        run: flutter build ipa --release

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install fastlane
        run: gem install fastlane --no-document

      - name: Create App Store Connect API key file
        env:
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          cat > asc_api_key.json << 'JSON'
          {
            "key_id": "${APP_STORE_CONNECT_KEY_ID}",
            "issuer_id": "${APP_STORE_CONNECT_ISSUER_ID}",
            "key": "${APP_STORE_CONNECT_PRIVATE_KEY}",
            "in_house": false
          }
          JSON

      - name: Upload to TestFlight (fastlane pilot)
        run: |
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n1)
          fastlane pilot upload \
            --api_key_path asc_api_key.json \
            --ipa "$IPA_PATH" \
            --skip_waiting_for_build_processing true \
            --verbose


